/* Generated by Yosys 0.47+22 (git sha1 f20f913223c42fce6ecc4382b281cf67952e0a72, g++ 14.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

(* top =  1  *)
(* src = "test12.v:2.1-11.10" *)
module main(a, b, c, d, e);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  (* src = "test12.v:3.20-3.21" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "test12.v:4.20-4.21" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "test12.v:5.20-5.21" *)
  input [3:0] c;
  wire [3:0] c;
  (* src = "test12.v:6.20-6.21" *)
  input [3:0] d;
  wire [3:0] d;
  (* src = "test12.v:7.21-7.22" *)
  output [7:0] e;
  wire [7:0] e;
  AND _31_ (
    .A(d[0]),
    .B(b[0]),
    .Y(_00_)
  );
  NAND _32_ (
    .A(d[1]),
    .B(b[1]),
    .Y(_01_)
  );
  XOR _33_ (
    .A(d[1]),
    .B(b[1]),
    .Y(_02_)
  );
  NAND _34_ (
    .A(_00_),
    .B(_02_),
    .Y(_03_)
  );
  XOR _35_ (
    .A(_00_),
    .B(_02_),
    .Y(e[1])
  );
  NAND _36_ (
    .A(_01_),
    .B(_03_),
    .Y(_04_)
  );
  NAND _37_ (
    .A(d[2]),
    .B(b[2]),
    .Y(_05_)
  );
  XOR _38_ (
    .A(d[2]),
    .B(b[2]),
    .Y(_06_)
  );
  NAND _39_ (
    .A(_04_),
    .B(_06_),
    .Y(_07_)
  );
  XOR _40_ (
    .A(_04_),
    .B(_06_),
    .Y(e[2])
  );
  NAND _41_ (
    .A(_05_),
    .B(_07_),
    .Y(_08_)
  );
  NAND _42_ (
    .A(d[3]),
    .B(b[3]),
    .Y(_09_)
  );
  XOR _43_ (
    .A(d[3]),
    .B(b[3]),
    .Y(_10_)
  );
  NAND _44_ (
    .A(_08_),
    .B(_10_),
    .Y(_11_)
  );
  XOR _45_ (
    .A(_08_),
    .B(_10_),
    .Y(e[3])
  );
  NAND _46_ (
    .A(_09_),
    .B(_11_),
    .Y(_12_)
  );
  ORNY _47_ (
    .A(c[0]),
    .B(a[0]),
    .Y(_13_)
  );
  XNOR _48_ (
    .A(a[0]),
    .B(c[0]),
    .Y(_14_)
  );
  NAND _49_ (
    .A(_12_),
    .B(_14_),
    .Y(_15_)
  );
  XOR _50_ (
    .A(_12_),
    .B(_14_),
    .Y(e[4])
  );
  AND _51_ (
    .A(_13_),
    .B(_15_),
    .Y(_16_)
  );
  AND _52_ (
    .A(a[0]),
    .B(a[1]),
    .Y(_17_)
  );
  XOR _53_ (
    .A(a[0]),
    .B(a[1]),
    .Y(_18_)
  );
  NAND _54_ (
    .A(c[1]),
    .B(_18_),
    .Y(_19_)
  );
  XNOR _55_ (
    .A(c[1]),
    .B(_18_),
    .Y(_20_)
  );
  OR _56_ (
    .A(_16_),
    .B(_20_),
    .Y(_21_)
  );
  XOR _57_ (
    .A(_16_),
    .B(_20_),
    .Y(e[5])
  );
  AND _58_ (
    .A(_19_),
    .B(_21_),
    .Y(_22_)
  );
  NAND _59_ (
    .A(a[2]),
    .B(_17_),
    .Y(_23_)
  );
  XNOR _60_ (
    .A(a[2]),
    .B(_17_),
    .Y(_24_)
  );
  ORNY _61_ (
    .A(c[2]),
    .B(_24_),
    .Y(_25_)
  );
  XOR _62_ (
    .A(c[2]),
    .B(_24_),
    .Y(_26_)
  );
  OR _63_ (
    .A(_22_),
    .B(_26_),
    .Y(_27_)
  );
  XOR _64_ (
    .A(_22_),
    .B(_26_),
    .Y(e[6])
  );
  NAND _65_ (
    .A(_25_),
    .B(_27_),
    .Y(_28_)
  );
  XNOR _66_ (
    .A(c[3]),
    .B(a[3]),
    .Y(_29_)
  );
  XNOR _67_ (
    .A(_23_),
    .B(_29_),
    .Y(_30_)
  );
  XNOR _68_ (
    .A(_28_),
    .B(_30_),
    .Y(e[7])
  );
  XOR _69_ (
    .A(d[0]),
    .B(b[0]),
    .Y(e[0])
  );
endmodule
